# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Browshot
version:      1.3.0
version_from: lib/WebService/Browshot.pm
installdirs:  site
requires:
    JSON:                          0
    LWP::Protocol::https:          0
    LWP::UserAgent:                0
    URI::Encode:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
